dist: trusty
language: node_js
node_js:
- '10.12.0'
script:
- npm run lint
- npm run build

before_deploy:
# move to dist
- cd dist
# update package versions
- npm version "${TRAVIS_TAG}" --no-git-tag-version --save
- if [[ "${TRAVIS_TAG}" == *"beta"* ]]; then export NPM_TAG="next"; else export NPM_TAG="latest"; fi

# copy readme
- cp ../../README.md README.md

deploy:
  provider: npm
  tag: "${NPM_TAG}"
  skip_cleanup: true
  email: igniteui@infragistics.com
  api_key:
    secure: DzxT8e3ryMBPMgx+6toU7+O+1nBLzjCAO4vyDQbze9Fi1jJ23PUUXuG9UmXqnzPUJ64uK4qzi40QiPdk4P0AsOiBr66fQtn02f/Yo1F42r13X9jKuqOdJlRl3dTWPGt5HOBO4YUq6BYA1HAh09/nsgLt670Wk2I8PMNpUiuTFI1F6vhGFsrjEaKbknrZhrQzfAxbTkbZe3RJmrEJQzU5CfFkZzoqsqpS20tFSSNiiPVy6G5OmAMW5f26klq5T0BZ0xBAf2AlXEmGo+LS+65Mbe+yQb1v/IUPk+YY4gwzQQEEh9d+MNU+tMOIVfkqyj5MIdILEIoLMlHKTtaqh8GsxOr2sFw6a4tTKpTqr4yBwuGspa/KjexC/41QVHQjaG0wAekuZluUOL+5I2jYzmVPAFSeiXhor4DFcp+Eh7uwEMaw1paX5DW8UiI8r2FU8RcHE75MN/EOSLE1+9He+RfxnHZW3MyOhOnvZt08+/WoFR6l1OpMM8mVVfHFFVvSk/QVbjFobbvzl5ecNMCS2H8EAJx8mYhwMgTxgf9Sw2AHKh0mgOlRBC9Ox17Hk2VKMcL7sgGY+7btP5mgqW1P/HHxXSAWaqS2e01L+GK5EG618R3Gz+Fphr6ZIyNqQ6BCc1UpJQZFJVVsPAJMMBg7Or5vcYJlxYPXOM5jLm8lzo9hSxA=
  on:
    tags: true
    repo: IgniteUI/igniteui-angular
