dist: trusty
language: node_js
node_js:
- '10.12.0'
script:
- npm run lint
- npm run build
# validate dist doesn't contain package imports:
- npm run lint-dist

before_deploy:
# copy files
- cp README.md dist/README.md
- cp package.json dist/package.json
- cp LICENSE dist/LICENSE
# move to dist
- cd dist
# update package versions
- npm version "${TRAVIS_TAG}" --no-git-tag-version --save
- if [[ "${TRAVIS_TAG}" == *"beta"* ]]; then export NPM_TAG="next"; else export NPM_TAG="latest"; fi

deploy:
  provider: npm
  tag: "${NPM_TAG}"
  skip_cleanup: true
  email: igniteui@infragistics.com
  api_key:
    secure: U5EN/FTlFcRcw2HxDzd4XinKyNS6hOdqoCLlgLucm8r7mu3CQmr7sOSzBB85OcnogvmqQASxhkXtmgOMIpYQRClUrkJi83D6jiKfx6gTqeTuqFVwatZEbSPbZLbIS84ARCC+hivJmtZ+6QoJLuBZ9IIxXJgJyC9qpq+Vh+e/IiTMVM1OOlFkov6xvXXofQkos5QDfJiFqz5zNsIvi7ruMN7DY6irpNFR3l1UYPARcqO2vv2lIvSoPQjt348fOgWfzFyJoSfpWNdncMscZiJlB/6MuyDP1/aCtWg/UdyYSt2YATyzNFt9DKv8uqhuZmjPSqw/CIyzntysUVcdyeAr+ZvO9XSoip/yZQMjxdgaQxbZLqJm6tpbzEmKoBnHVloFX/CyfVJtnx4q3UfBWu0PrKyYMGqrCSAkTIrdC8D5W7FivB3S1afQ1971saWRHaSXuPixm43R8CVdkcCH+1Yxz582t0xy02mr00bmuMDuTKKXr6iZI5ywB1Fj1/SwLl4RPm3JFdcmQjrmRpCIdeqJuQr1Og89pw5g4zF+c+fguttS2VhFzVJ3uiJO/9/uSUzBBcbP1CeLwYEQ6ZQmZzIIazroSJynJti0Cv9Aj5nNUONdWDi+4t9Iz8cE8A0twWSt4mdqji+dLYV4csHULiKs4/CAoRkWcKPN47JKNsNcyHY=
  on:
    tags: true
    repo: IgniteUI/igniteui-angular-i18n
